### ISSUE TITLE
Odd Error Using Angular CLI for AoT

### ISSUE THREAD

**Issue by NathanLawrence** [Gbuomprisco/ng2-tag-input#106]
I keep getting this error when I add `TagInputModule` to my imports:

```
Error: TagInputModule is not an NgModule
    at AotPlugin.getNgModuleMetadata (/Users/nathanlawrence/Documents/KBIA Dev/accessmo-ng/node_modules/@ngtools/webpack/src/plugin.js:332:19)
    at /Users/nathanlawrence/Documents/KBIA Dev/accessmo-ng/node_modules/@ngtools/webpack/src/plugin.js:345:51
    at Array.map (native)
    at AotPlugin.extractLoadChildren (/Users/nathanlawrence/Documents/KBIA Dev/accessmo-ng/node_modules/@ngtools/webpack/src/plugin.js:343:14)
    at AotPlugin._processNgModule (/Users/nathanlawrence/Documents/KBIA Dev/accessmo-ng/node_modules/@ngtools/webpack/src/plugin.js:272:38)
    at /Users/nathanlawrence/Documents/KBIA Dev/accessmo-ng/node_modules/@ngtools/webpack/src/plugin.js:242:39
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Am I doing something ridiculous, or is this an actual bug? I checked TagInputModule's declaration, and it's preceded by an `@NgModule` decorator just as it should be -- in fact, the code is basically *just* the decorator. So what's going on?

**Comment by avinashjoshi** [comment]
I have the same issue!

**Comment by Gbuomprisco** [comment]
Hi @NathanLawrence and @avinashjoshi,

there are a few issues listed with AoT. Unfortunately when I built it I didn't take it into consideration (I started this while it was in beta). I am going to have a look though now and solve it :)

**Comment by Gbuomprisco** [comment]
HI @NathanLawrence  and @avinashjoshi,

the latest version *should* be working with AOT. I am trying with some boilerplates but some 3rd parties always complain. Please reopen if still not working

**Comment by avinashjoshi** [comment]
It works! Thanks @Gbuomprisco

**Comment by jsfrocha** [comment]
Hi @Gbuomprisco, I'm still unable to make it work with AoT compilation with the Angular CLI.

However, it seems that the latest `master` branch should fix my problem, could you please publish it to NPM ?

Thanks.

**Comment by Gbuomprisco** [comment]
Hi @jsfrocha,

I published the latest version yesterday. Which one are you getting?

**Comment by jsfrocha** [comment]
Oh, okay, I just did a `npm cache clean` and reinstalled everything, but I'm still getting the:

`ERROR in TagInputModule is not an NgModule`

**Comment by Gbuomprisco** [comment]
Yeah that's an error happening since angular-cli 2.25 (are you using this?). I haven't found a solution for this yet :(

**Comment by jsfrocha** [comment]
Did you mean 25.5 ?

I'm using `"angular-cli": "1.0.0-beta.25.5"`

**Comment by Gbuomprisco** [comment]
Right, sorry :) Yes, since that version that error appears ..

**Comment by jsfrocha** [comment]
Okay, I'll take a look and get back to you if I can find something.

**Comment by Gbuomprisco** [comment]
That would be great @jsfrocha!

**Comment by anil-agrawal** [comment]
Update module declaration file ng-input.module.d.ts as below

import { Options } from './core';
import { NgModule } from '';
@NgModule() export declare class TagInputModule {
static withDefaults(options: Options): void;
}
