### ISSUE TITLE
Tag-Input inside 'form' does not render its' tags until input is touched

### ISSUE THREAD

**Issue by RamTararam** [Gbuomprisco/ng2-tag-input#16]
Hi. I've noticed some issue in component rendering when I placed `tag-input` inside `<form></form>`. Initial values are not rendered until input is touched in my case.

I've created a [demo](http://plnkr.co/edit/Uos1lUIWJHKqBJBaRUpn?p=preview) that briefly mirrors my original situation.

**Comment by Gbuomprisco** [comment]
Hi! 

I published the version 0.1.5 which should fix this. I updated your demo: http://plnkr.co/edit/ZksPMxG85ZvOA68XzDx2?p=preview

**Comment by RamTararam** [comment]
Thanks! It is working as expected now

**Comment by touqeershafi** [comment]
I'm still facing this issue is there any `refresh()`  method exists ?

btw plucker demo is not working.

**Comment by Gbuomprisco** [comment]
This issue is very old. Try adding a name attribute to the component

**Comment by touqeershafi** [comment]
@Gbuomprisco still getting the same issue, even though i've also updated the package to `"ng2-tag-input": "^1.4.0",`


```html
<tag-input name="sourceTags" [(ngModel)]="source.sourceTags" [identifyBy]="'tag'" [displayBy]="'tag'" #tagInput></tag-input>
```

```typescript
this.sourceService.getSource(localSource.id).subscribe((source: Source) => {
      this.source = new Source(source);
      this.isBusySource = false;
      this.changeDetector.markForCheck(); // <-- markForCheck because i'm using changeDetection: ChangeDetectionStrategy.OnPush
    });
```

**Comment by Gbuomprisco** [comment]
In my experience using onPush was the reason of the issue which is why I removed it, try without maybe?

**Comment by Gbuomprisco** [comment]
In my experience using onPush was the reason of the issue which is why I removed it, try without maybe?

**Comment by touqeershafi** [comment]
Np it's not working, same experience when i click on `input` field then it populates the existing tags.

**Comment by Gbuomprisco** [comment]
Sorry not sure what the issue is..

**Comment by touqeershafi** [comment]
Just Temp thing is to pushed tags manually in component:

```typescript
@ViewChild("tagInput") tagInput: TagInputComponent;

this.sourceService.getSource(localSource.id).subscribe((source: Source) => {
      this.source = new Source(source);
      this.isBusySource = false;
      this.source.sourceTags.forEach(($item) => {
        this.tagInput.appendTag({tag: $item.tag});
      });

      this.changeDetector.markForCheck();
    });
```

**Comment by Gbuomprisco** [comment]
guess `onTouched()` should also work

**Comment by touqeershafi** [comment]
@Gbuomprisco in my case `onTouched()` is also not working.
