### ISSUE TITLE
Exception in Ng2DropdownModule after migrating project to Angular4

### ISSUE THREAD

**Issue by okachynskyy** [Gbuomprisco/ng2-tag-input#298]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
Uncaught exception in browser console:
```
ERROR Error: Uncaught (in promise): Error: Found the synthetic property @fade. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.
Error: Found the synthetic property @fade. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.
    at checkNoSyntheticProp (vendor.bundle.js:40984) [angular]
    at EmulatedEncapsulationDomRenderer2.DefaultDomRenderer2.setProperty (vendor.bundle.js:40952) [angular]
    at DebugRenderer2.setProperty (vendor.bundle.js:13666) [angular]
    at setElementProperty (vendor.bundle.js:9943) [angular]
    at checkAndUpdateElementValue (vendor.bundle.js:9862) [angular]
    at checkAndUpdateElementInline (vendor.bundle.js:9802) [angular]
    at checkAndUpdateNodeInline (vendor.bundle.js:12487) [angular]
    at checkAndUpdateNode (vendor.bundle.js:12462) [angular]
    at debugCheckAndUpdateNode (vendor.bundle.js:13091) [angular]
    at debugCheckRenderNodeFn (vendor.bundle.js:13070) [angular]
    at Object.eval [as updateRenderer] (ng:///Ng2DropdownModule/Ng2DropdownMenu.ngfactory.js:300) [angular]
    at Object.debugUpdateRenderer [as updateRenderer] (vendor.bundle.js:13055) [angular]
    at checkAndUpdateView (vendor.bundle.js:12434) [angular]
    at callViewAction (vendor.bundle.js:12744) [angular]
    at checkNoSyntheticProp (vendor.bundle.js:40984) [angular]
    at EmulatedEncapsulationDomRenderer2.DefaultDomRenderer2.setProperty (vendor.bundle.js:40952) [angular]
    at DebugRenderer2.setProperty (vendor.bundle.js:13666) [angular]
    at setElementProperty (vendor.bundle.js:9943) [angular]
    at checkAndUpdateElementValue (vendor.bundle.js:9862) [angular]
    at checkAndUpdateElementInline (vendor.bundle.js:9802) [angular]
    at checkAndUpdateNodeInline (vendor.bundle.js:12487) [angular]
    at checkAndUpdateNode (vendor.bundle.js:12462) [angular]
    at debugCheckAndUpdateNode (vendor.bundle.js:13091) [angular]
    at debugCheckRenderNodeFn (vendor.bundle.js:13070) [angular]
    at Object.eval [as updateRenderer] (ng:///Ng2DropdownModule/Ng2DropdownMenu.ngfactory.js:300) [angular]
    at Object.debugUpdateRenderer [as updateRenderer] (vendor.bundle.js:13055) [angular]
    at checkAndUpdateView (vendor.bundle.js:12434) [angular]
    at callViewAction (vendor.bundle.js:12744) [angular]
    at resolvePromise (polyfills.bundle.js:5250) [angular]
    at resolvePromise (polyfills.bundle.js:5221) [angular]
    at :4200/polyfills.bundle.js:5298:17 [angular]
    at Object.onInvokeTask (vendor.bundle.js:4493) [angular]
    at ZoneDelegate.webpackJsonp.991.ZoneDelegate.invokeTask (polyfills.bundle.js:4935) [angular]
    at Zone.webpackJsonp.991.Zone.runTask (polyfills.bundle.js:4703) [<root> => angular]
    at drainMicroTaskQueue (polyfills.bundle.js:5131) [<root>]
```

**Expected behavior**
No exception in browser console.

**Minimal reproduction of the problem with instructions**
I have migrated my project to Angular4.0.0 and I get this exception in browser console.

**What do you use to build your app? (SystemJS, Webpack). Please specify the version**
Angular CLI 1.0.0

* **Angular version:** 4.0.0

* **Browser:**  [ Chrome XX | Firefox XX |  Safari XX | Opera XX ]

**Comment by Gbuomprisco** [comment]
Hi @okachynskyy,

thanks for reporting - will look into it later today

**Comment by Gbuomprisco** [comment]
Hi @okachynskyy,

this should now be solved - try the latest version :)

**Comment by okachynskyy** [comment]
@Gbuomprisco thanks for reply :)
After updating to 1.0.1 I have the same issue: https://github.com/Gbuomprisco/ng2-tag-input/issues/300

In 1.0.0 I still have this exception without importing BrowserAnimationsModule.
